### ISSUE TITLE
exceptionSearchingForPersistenceResources - java.lang.NullPointerException

### ISSUE THREAD

**Issue by muratneciparcans** [kumuluz/kumuluzee-samples#10]
I'm having issue when I try to start JPA example in kumuluzee-samples repository

![screen shot 2018-05-13 at 3 08 35 pm](https://user-images.githubusercontent.com/17123908/39967645-931f46f2-56bf-11e8-8ffc-7088e41e857c.png)

**Comment by jmezna** [comment]
Which version of Java are you using? KumuluzEE version 2.5.2 works with Java version 8. For Java 9 or 10 you must use KumuluzEE 3 (which is currently a beta release https://github.com/kumuluz/kumuluzee/releases/tag/v3.0.0-beta.1),

**Comment by cen1** [comment]
This exception can be observed when running kumuluzee 2.X with Java 9+.
