### ISSUE TITLE
LocalDate support

### ISSUE THREAD

**Issue by santoshreddy17** [kumuluz/kumuluzee-samples#13]
Is there support for LocalDate object through rest interface ?
I get this issue when i pass simple date '2018-07-26' or complex one with '2018-07-26T09:03:44.867Z'
Any solutions or ideas ?

Can not construct instance of java.time.LocalDate: no String-argument constructor/factory method to deserialize from String value ('2018-07-26T09:03:44.867Z')
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@3e86c150; line: 5, column: 21] (through reference chain: com.lgim.nexus.omsadapter.domain.object.fx.order.SingleFxOrder["settlementDate"])

**Comment by jmezna** [comment]
Deserialisation in JAX-RS is done by Jackson. You can configure it with a simple mapper: 

`
@Provider
public class JacksonProvider implements ContextResolver<ObjectMapper> {

    private final ObjectMapper mapper;

    public JacksonProvider() {
        mapper = new ObjectMapper();
        mapper.configure(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS, false);
    }

    @Override
    public ObjectMapper getContext(Class<?> type) {
        return mapper;
    }
}
`

**Comment by santoshreddy17** [comment]
@jmezna 

we are still having same issues even with the provide. 

Can not construct instance of java.time.LocalDate: no String-argument constructor/factory method to deserialize from String value ('2018-07-26')
 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@73bb9c0; line: 2, column: 16] (through reference chain: com.blah.mooh.Blah["localDate"])

I am sending this request to swagger: 
{
  "localDate": "2018-07-26",
  "mooh": "mpooooooohhhh"
}

**Comment by jmezna** [comment]
By default, deserializer expects the same string format as is returned by the serializer. This can help you determining the expected format. 

You can further configure the serialisation of LocalDate type using the dependency

```xml
<dependency>
    <groupId>com.fasterxml.jackson.datatype</groupId>
    <artifactId>jackson-datatype-jsr310</artifactId>
    <version>2.8.10</version>
</dependency>
```

and registering the Java time module in the provider

```java
mapper.registerModule(new JavaTimeModule());
```

**Comment by cen1** [comment]
Registering JavaTimeModule is adequate.
