### ISSUE TITLE
Unsatisfied dependencies for type KeycloakSecurityConfigurationUtilImpl with qualifiers @Default

### ISSUE THREAD

**Issue by leccyril** [kumuluz/kumuluzee-samples#23]
hello, 

i have a wildfly server i just added dependancies as your exemple CDI integration bu i have this error

Unsatisfied dependencies for type KeycloakSecurityConfigurationUtilImpl with qualifiers @Default

any idea ?

**Comment by cen1** [comment]
Some of the extensions rely on kumuluzee framework dependencies so simply copying the extensions to wildfly is not necesserily going to work. Wildfly already ships with it's own CDI implementation and keycloak has a dedicated adapter for wildfly so that is what you should probably use.
