### ISSUE TITLE
add testing examples

### ISSUE THREAD

**Issue by remmeier** [kumuluz/kumuluzee-samples#6]
the examples here look all great. However, one thing I have missed on first sight from all the examples and the website: testing/junit.

is there already something in place? With the Deltaspike CDI Test Runner and the Weld integration, that should be a fairly simple thing to achieve?

**Comment by MBJuric** [comment]
Hi, 
For testing, you can use any testing framework, such as JUnit or Rest-assured. All frameworks work with KumuluzEE. 
You only have to make sure to start the KumuluzEE microservice before running the tests. You can do this automatically in the pre-test Maven phase. 
We will add testing samples shortly.
Best regards,
Matjaz

**Comment by remmeier** [comment]
are you aware of the Deltaspike CDI JUnit runner? This way there is no separation between the application and test cases (just like in Spring).  I can hit JUnit run in my IDE, Maven, Gradle, etc, it will launch my CDI environment (like kumuluzEE I hope), execute the test(s) and tear it down again. Further benefit is that the test cases gain access to the CDI environment, so I can do and test things that are not accessible when just accessing the pre-test-maven resp. remote HTTP endpoint.

**Comment by remmeier** [comment]
(we are using it extensively to test applications before deploying them into wildfly)

**Comment by cen1** [comment]
Arquillian testing is explained in [kumuluzee-testing](https://github.com/kumuluz/kumuluzee-testing) extension. As far as JUnit is concerned there is nothing specific about kumuluz there. CDI can be easily tested with weld-junit and is also a generic solution.

If someone encounters a specific problem with unit testing and KumuluzEE, open a new issue.
