### ISSUE TITLE
Not working with Java 9 or later (kumuluzee-swagger and kumuluzee-openapi)

### ISSUE THREAD

**Issue by TapaniRundgren** [kumuluz/kumuluzee-samples#9]
Get this message when running kumuluzee-samples/kumuluzee-swagger:
2018-04-25 09:09:41,331 WARN  Multiple JAX-RS applications not supported. Swagger definitions will not be served. {}
And no swagger ui available
Both works without problems with Java 8

**Comment by zvonegit** [comment]
We've added support for Java 9/10 and updated the samples.
The following snapshot versions provide support for Java 9/10:
 - kumuluzee-swagger: 1.1.0-SNAPSHOT
 - kumuluzee-openapi: 1.0.0-SNAPSHOT

Both extensions will be released soon.

**Comment by santoshreddy17** [comment]
Is there an update on when the official 1.0.0 version will be released ?
